version: '3.8'

services:
  mariadb:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
#    command: --init-file /docker-entrypoint-initdb.d/grant_permissions.sql
    networks:
      custom_network:
        ipv4_address: 172.20.0.2

volumes:
  mariadb_data:

networks:
  custom_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16